#*      makefile
#*
#* Make script for common document files - only does cleanup
#*
#* $Id: makefile,v 1.2 1997/07/31 10:56:34 pekangas Exp $
#*
#* Copyright 1996,1997 Housemarque Inc.
#*
#* This file is part of MIDAS Digital Audio System, and may only be
#* used, modified and distributed under the terms of the MIDAS
#* Digital Audio System license, "license.txt". By continuing to use,
#* modify or distribute this file you indicate that you have
#* read the license and understand and accept it fully.
#*

# A dummy default target:
all :


# Get cleanup rules from common.mak:
include common.mak
